{% set name = "ttim" %}
{% set version = "0.6.4" %}

package:
  name: {{ name |lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 7ee4b85314a0f443e2b1b690772f5932c93d8367b6d17197d895816ad693d12c

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.7
    - pip
    - setuptools_scm
  run:
    - python >=3.7
    - lmfit >=1.0
    - matplotlib-base
    - numba >=0.5
    - numpy >=1.17
    - pandas >=1.1
    - scipy >=1.5

test:
  imports:
    - ttim

about:
  home: https://github.com/mbakker7/ttim
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Transient multi-layer AEM Model
  dev_url: https://github.com/mbakker7/ttim

extra:
  recipe-maintainers:
    - jentjr
    - mbakker7
    - Huite
